/** 홍익대학교 QR코드의 경우 0학번 1발급일 형태의 데이터 포함*/
const STUDENT_ID_SINDEX = 1;
const STUDENT_ID_LENGTH = 7;
const ISSUED_DAY_SINDEX = STUDENT_ID_SINDEX+STUDENT_ID_LENGTH+1;
const ISSUED_DAY_LENGTH = 14;

export const hongikQrFormat = [STUDENT_ID_SINDEX, STUDENT_ID_LENGTH, ISSUED_DAY_SINDEX, ISSUED_DAY_LENGTH];